const userConstants: any = {
    USER_TOKEN: 'USER_TOKEN_TEMPLATE_TOKEN',
    LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
    LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
    LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',
    LOGOUT: 'USERS_LOGOUT',

    USER_ACCOUNT: 'USER_ACCOUNT',
    USER_ACCOUNT_REQUEST: 'USER_ACCOUNT_REQUEST',
    USER_ACCOUNT_SUCCESS: 'USER_ACCOUNT_SUCCESS',
    USER_ACCOUNT_FAILURE: 'USER_ACCOUNT_FAILURE',
    USER_ACCOUNT_REMOVE: 'USER_ACCOUNT_REMOVE',
    USER_ACCOUNT_PROFILE_ID: 'USER_ACCOUNT_PROFILE_ID',
}

export default userConstants;